# Generated by Django 3.0 on 2020-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id_anio', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidadAlumnos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('horarioCursado', models.DateTimeField()),
                ('diaCursado', models.DateField()),
            ],
        ),
    ]
