# Generated by Django 3.0 on 2020-09-15 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='nombre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='institucion.Institucion'),
            preserve_default=False,
        ),
    ]
