# Generated by Django 3.0 on 2020-09-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_aula_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='id_anio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='institucion.Anio'),
            preserve_default=False,
        ),
    ]
