# Generated by Django 3.0 on 2020-09-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('tutor', models.CharField(max_length=60)),
                ('año', models.IntegerField(max_length=1)),
                ('division', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=69)),
                ('dni', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('fechaNacimiento', models.DateField()),
                ('telefono', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
