# Generated by Django 3.0 on 2020-09-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200905_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('horarioCursado', models.DateTimeField()),
                ('diaCursado', models.DateField()),
            ],
        ),
    ]
