# Generated by Django 3.0 on 2020-09-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200914_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anio',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
