# Generated by Django 3.0 on 2020-09-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20200915_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_profesor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
