# Generated by Django 3.0 on 2020-09-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_materia_id_anio'),
        ('usuario', '0007_usuario_es_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='anio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='institucion.Anio'),
            preserve_default=False,
        ),
    ]
